### ISSUE TITLE
504 channel/connection is not open after a few minutes

### ISSUE THREAD

**Issue by Jamalianpour** [rabbitmq/amqp091-go#102]
Hello,
I have one channel with 2 queue and after a few minutes (about 15 minutes) I got 504 error :
`Exception (504) Reason: channel/connection is not open`
My code:
```go
RabbitConnection, err := rabbitmq.Dial("amqp://" + username + ":" + password + "@" + host + "/")
if err != nil {
	return err
}

//conn.Close()
RabbitChannel, err = RabbitConnection.Channel()
if err != nil {
	return err
}
//RabbitChannel.Close()

_, err = RabbitChannel.QueueDeclare(
	LsQueue, // name
	true,   // durable
	false,   // delete when unused
	false,   // exclusive
	false,   // no-wait
	nil,     // arguments
)
_, err = RabbitChannel.QueueDeclare(
	CoreQueue, // name
	true,     // durable
	false,     // delete when unused
	false,     // exclusive
	false,     // no-wait
	nil,       // arguments
)

err = RabbitChannel.Confirm(false)
if err != nil {
	return err
}
```

**Comment by lukebakken** [comment]
The code you provided does not compile as-is, nor is it runnable. You _must_ provide code that I can compile and run, with instructions on how to run it. We don't have time to guess how to reproduce your issue.

Based on the _incomplete_ set of code you provided, there should be no issue.

Please let us know what RabbitMQ logs at the time of the error.
