### ISSUE TITLE
Provide a friendly way to set connection name

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/amqp091-go#105]
The [client provided connection name](https://rabbitmq.com/api-guide.html#client-provided-names) is very useful to identify connections in Management UI and during debugging sessions. In the Java Client, it's quite easy to set a client provided name with `ConnectionFactory.newConnection(string clientName)`. In this client, a user has to set a configuration property with a specific name, for example:

```golang
connection, err := amqp.DialConfig(
		amqpURI,
		amqp.Config{Properties: map[string]interface{}{"connection_name": "sample-producer"}},
	)
```

This isn't great because the user is required to know the property key `connection_name` and the `Properties` map has to be crafted manually.

We should either provide a simple function like `amqp.SetConnectionName(amqp.Config, string)`, or a constant with the connection name key (and any other well-known properties).

**Comment by lukebakken** [comment]
Is this documented at least?

Seems like providing a way to build the `Config`'s `Properties` map could work.
