### ISSUE TITLE
Support connection.update-secret 

### ISSUE THREAD

**Issue by MatthiasWerning** [rabbitmq/amqp091-go#107]
The AMQP 0-9-1 reference guide at https://www.rabbitmq.com/amqp-0-9-1-reference.html#connection.update-secret describes a method to update a secret / password on existing connections without having to disconnect and reconnect again. This makes things a lot easier if authentication is done using the rabbitmq_auth_backend_oauth2 which comes with JWT tokens that have a certain lifespan. If such a token expires and it is not updated, this results in a unusable connection. Updating the token results in a usable connection again without having to deal with the hassle of reconnecting and thus having to resubscribe consumers.

Would be very nice if this could be supported in future versions as we heavily depend on this feature for authentication and authorization means in our backend.

**Comment by lukebakken** [comment]
@MatthiasWerning I just tagged version 1.5.0 which has support for `connection.update-secret`
