### ISSUE TITLE
copyright issue?

### ISSUE THREAD

**Issue by pabigot** [rabbitmq/amqp091-go#12]
It's great that this project is being actively maintained.  While investigating a race condition I noticed that 65f6e252100da62430f7fa5074d7985f8e2f45d2 updated the source code link in the code files, but simultaneously **replaced** the existing copyright in the code files with one for VMWare or affiliates, rather than just adding the new claim.

Based on changes in other commits such as 34291f5dde8296e3863cab64b3d5486969ff8cd5 I believe the VMWare copyright should have been added to the files, leaving the existing copyright in place.  Unless the original contributors to this project have formally transferred their rights to VMWare?

**Comment by Zerpet** [comment]
Commit e2e2d97 fixes this, and adds copyright to some files that were missing the license header. Thanks for reporting this!
