### ISSUE TITLE
Publishing Headers are unable to store Table with slice values

### ISSUE THREAD

**Issue by jkbmdk** [rabbitmq/amqp091-go#125]
I'm trying to publish message similar to:
```
channel.PublishWithContext(
        ctx,
        exchange,
        messageName,
        false,
        false,
        amqp091.Publishing{
            ContentType:  "application/json",
            ContentEncoding: "utf-8",
            Body:  payload,
            Headers: amqp091.Table{"_trace": []string{"a", "b"}},
        }
)
```
and i receive error
`table field "_trace" value []string not supported`
I guess problem lies on slice validation https://github.com/streadway/amqp/blob/master/types.go#L232, shouldn't it be done using reflect? 
Passing strings vector is not a problem via PHP amqp lib, so it seems to me that this is not the limitation of a rabbitmq.

I'm using
- go version 1.18.1
- amqp091-go v1.5.0

**Comment by lukebakken** [comment]
> Passing strings vector is not a problem via PHP amqp lib

My guess is that the PHP library is able to serialize the data for you. It would be interesting to see what you are doing, so please provide some code I can run to see how this works in PHP.

In your case you should serialize `[]string{"a", "b"}` to a string or binary value, and use that as the value for `_trace` - https://github.com/rabbitmq/amqp091-go/blob/main/types.go#L210-L230

**Comment by jkbmdk** [comment]
Sending an unserialised vector it's propably buildin rabbit feature. I have not found any serialisation in PHP lib and also you are able to publish list using rabbit gui:
![image](https://user-images.githubusercontent.com/25589855/194814560-795fda3f-08a9-401d-af5f-97c48e13a3dc.png)
 and that's the way rabbit displays message with list in header
![image](https://user-images.githubusercontent.com/25589855/194814700-173592a4-5fc4-43aa-a20c-c9e89d4b4a70.png)
also comment in https://github.com/streadway/amqp/blob/master/types.go#L213 suggests that you should be able to pass e.g. `[]string` to header value. Today I'll try to create pull request with a fix proposal

**Comment by Zerpet** [comment]
I'm not sure we claim to have support for `[]string` values, based on https://pkg.go.dev/github.com/rabbitmq/amqp091-go#Table

I'm happy to review a PR to add support for lists of supported AMQP types.

**Comment by jkbmdk** [comment]
It seems like i do not have an access to create pull request
```
$ git push -u origin slice-field-validation-fix
ERROR: Permission to rabbitmq/amqp091-go.git denied to jkbmdk.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
