### ISSUE TITLE
README not up to date

### ISSUE THREAD

**Issue by scriptcoded** [rabbitmq/amqp091-go#154]
The [following section](https://github.com/rabbitmq/amqp091-go/blob/main/README.md?plain=1#L40-L41) in the README

> We expect this client to undergo moderate breaking public API changes in 2021. Major and minor versions will be updated accordingly.

says there will be breaking changes in 2021. It appears we're in 2023 now :tada: I'm unaware of what these breaking changes are or if they're implemented, but perhaps the README should be revised :smile:

**Comment by lukebakken** [comment]
We welcome pull requests, even for small things like updating the README. Thanks.

**Comment by scriptcoded** [comment]
@lukebakken Raised https://github.com/rabbitmq/amqp091-go/pull/155. Though as I said I'm not aware of what changes are being referred to. Seeing as the last tag here on GitHub is 1.1.0 from September 2021 I can only assume these changes have been made and the paragraph should simply be removed. Please tell me if this assumption is incorrect.

**Comment by lukebakken** [comment]
Fixed by #155
