### ISSUE TITLE
The ctx parameter in the PublishWithDeferredConfirmWithContext method does not have a contextual effec

### ISSUE THREAD

**Issue by xiaozhaofu** [rabbitmq/amqp091-go#210]
Thank you for reading my question，I am using version 1.8.1 of amqp091-go, In the channel. go file, the ctx parameter of the PublishWithDeferredConfirmWithContext method does not control the context, but there is a judgment on line 1427, but it cannot be used to determine whether to terminate the run，I hope you can help me check the problem, thank you

**Comment by Zerpet** [comment]
I'm afraid most maintainers of this client don't speak Chinese. If you can update your description in English, I will be happy to triage this issue.

**Comment by xiaozhaofu** [comment]
> 



> I'm afraid most maintainers of this client don't speak Chinese. If you can update your description in English, I will be happy to triage this issue.

Thank you for reading my question，I am using version 1.8.1 of amqp091-go, In the channel. go file, the ctx parameter of the PublishWithDeferredConfirmWithContext method does not control the context, but there is a judgment on line 1427, but it cannot be used to determine whether to terminate the run，I hope you can help me check the problem, thank you

**Comment by Zerpet** [comment]
You are correct. Function `PublishWithDeferredConfirmWithContext` does not obey context cancellation. `Channel` struct uses an RPC engine. This RPC engine is used to communicate with RabbitMQ. This RPC engine was designed before Golang had `context` package. At the moment, it is not possible to cancel an RPC request. We can check context cancellation before calling `ch.send()`. Would that help you?

For example:

```go
func (ch *Channel) PublishWithDeferredConfirmWithContext(ctx context.Context, exchange, key string, mandatory, immediate bool, msg Publishing) (*DeferredConfirmation, error) {
        // ....
        select {
	default:
	case <-ctx.Done():
		return nil, ctx.Err()
	}

	var dc *DeferredConfirmation
	if ch.confirming {
		dc = ch.confirms.publish()
	}

	if err := ch.send(&basicPublish{....}
        // ....
```

**Comment by xiaozhaofu** [comment]
> 

Thank you very much for your guidance. I understand what needs to be done. Thank you
