### ISSUE TITLE
OpenTelemetry Propagation

### ISSUE THREAD

**Issue by brianmori** [rabbitmq/amqp091-go#22]
Hi,

I would like to ask if [OpenTelemetry](https://opentelemetry.io/docs/go/getting-started/) support should be part of this library.  

When a service A communicate through rabbitmq to service B, service A needs to propagate the "TraceID" and "SpanID" to service B to measure the time needed.

I saw this issue which may help:
https://github.com/open-telemetry/opentelemetry-go-contrib/issues/376

**Comment by DanielePalaia** [comment]
There is a discussion to add support for Open Telemetry, but not a short term plan. Let's keep this Issue https://github.com/rabbitmq/amqp091-go/issues/43 to track the advancements
