### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by listeriaceae** [rabbitmq/amqp091-go#231]
### Describe the bug

in the comment above the QueueUnbind channel method ([channel.go:975](https://github.com/rabbitmq/amqp091-go/blob/main/channel.go#L974C1-L976C44)) it states the following:
> It is possible to send and empty string for the exchange name which means to
> unbind the queue from the default exchange.

but in the management UI under Exchanges > (AMQP default) > Bindings is says (_emphasis mine_):
> The default exchange is implicitly bound to every queue, with a routing key equal to the queue name. It is not possible to explicitly bind to, _or unbind from the default exchange_. It also cannot be deleted.

Also tried it and got an error: `Failed to unbind queue: Exception (403) Reason: "ACCESS_REFUSED - operation not permitted on the default exchange"`

### Reproduction steps

1. Read the comment
2. Read the docs
3. Confusion

### Expected behavior

1. Read the comment
2. Read the docs
3. Consistency

**Comment by Zerpet** [comment]
Indeed it is not allowed to bind/unbind from the default exchange. We deviate from the spec in that regards. I will update our web docs. The comment is removed via a6fa7f7d76ecb00f1f46d42d02adfe0454c5514f
