### ISSUE TITLE
No access to this vhost

### ISSUE THREAD

**Issue by lscgzwd** [rabbitmq/amqp091-go#24]
```
// dns: amqp://customservice:customservice123@IP:5672/zssb
mqConn, err = amqp.Dial(mq.dns)
```
![image](https://user-images.githubusercontent.com/7054255/140051241-e85f0a55-e140-41d5-9e1c-8e7276478449.png)
![image](https://user-images.githubusercontent.com/7054255/140051298-8c491975-b052-4064-8fdd-1f70c3b8f115.png)
![image](https://user-images.githubusercontent.com/7054255/140051638-4f086a77-a8d2-42bc-b9b2-f60410b63a2b.png)

Exception (403) Reason: "no access to this vhost"

**Comment by lukebakken** [comment]
Thanks for using RabbitMQ.

According to the information you have provided there should be no issue. I suggest doing the following to help us help you:

* Run [this command](https://www.rabbitmq.com/rabbitmqctl.8.html#authenticate_user) on your RabbitMQ server to confirm authentication works:
    ```
    rabbitmqctl authenticate_user customservice customservice123
    ```
    When you run this command, capture the output into a file and attach the file to your response.
* Provide _exact_ instructions for reproducing this problem. How did you create the user? How did you grant permissions? Can you reproduce this problem every time without fail?

**Comment by lscgzwd** [comment]
the reason is need double slash.

**Comment by lscgzwd** [comment]
> Thanks for using RabbitMQ.
> 
> According to the information you have provided there should be no issue. I suggest doing the following to help us help you:
> 
> * Run [this command](https://www.rabbitmq.com/rabbitmqctl.8.html#authenticate_user) on your RabbitMQ server to confirm authentication works:
>   ```
>   rabbitmqctl authenticate_user customservice customservice123
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   When you run this command, capture the output into a file and attach the file to your response.
> * Provide _exact_ instructions for reproducing this problem. How did you create the user? How did you grant permissions? Can you reproduce this problem every time without fail?

I have provided the management screenshot, it shows the account has permission to that vhost, and the account is correct used in springboot.

the reason is in golang, it need double slash, but there are not have any document point out that.

// dns: amqp://customservice:customservice123@IP:5672//zssb

**Comment by lukebakken** [comment]
> the reason is need double slash

Oh, indeed. I didn't notice the fact that your vhost name starts with a slash character (`/zssb`).

> the reason is in golang, it need double slash, but there are not have any document point out that.

This isn't just limited to Go. Any client that connects to a vhost named `/zssb` would use an AMQP URI like the following:

```
amqp://customservice:customservice123@IP:5672//zssb
```

You might consider URI-encoding the vhost name, so that the above becomes this:

```
amqp://customservice:customservice123@IP:5672/%2Fzssb
```

**Comment by vigamage** [comment]
> the reason is need double slash.

 I am sorry, where is this documented ?

**Comment by lukebakken** [comment]
@vigamage there is no relevant documentation, because there is no special case going on here.

@lscgzwd is using a vhost with the literal name `/zssb`. Vhost names are **NOT** in a hierarchy like a filesystem, so `/zssb` has **NO** relationship to the default vhost that is named `/`.
