### ISSUE TITLE
republishing on reconnect bug in the example

### ISSUE THREAD

**Issue by Boris-Plato** [rabbitmq/amqp091-go#249]
### Describe the bug

I found [this your example](https://github.com/rabbitmq/amqp091-go/blob/main/_examples/pubsub/pubsub.go) on how to implement a beautiful reconnect logic. I assume that [pending channel](https://github.com/rabbitmq/amqp091-go/blob/main/_examples/pubsub/pubsub.go#L98) that we use for [retry failed delivery on the next session](https://github.com/rabbitmq/amqp091-go/blob/main/_examples/pubsub/pubsub.go#L134) should be moved out of sessions for loop f.e. to the line 93. I made a test simulating error on publishing and the message was not republished to the new session with the current version of an example. When I moved pending channel out of the sessions loop it worked fine. I can provide some code examples if it is required.

### Reproduction steps

1) simulate 1 time error on publishing and call
pending <- body
pub.Close()
break Publish
2) send a message and check if it was republished and correctly processed with the subscriber

### Expected behavior

message republished to the new reconnected session

**Comment by lukebakken** [comment]
Hello, thanks for using this library

If you have a fix for the example, please submit a pull request to fix the example.

**Comment by Boris-Plato** [comment]
Here we go
https://github.com/rabbitmq/amqp091-go/pull/250/files
