### ISSUE TITLE
QueueDeclarePassive does not report queue type mismatch

### ISSUE THREAD

**Issue by gildas** [rabbitmq/amqp091-go#273]
**Describe the bug**
channel.QueueDeclarePassive succeeds with existing queue of different type.

**To Reproduce**
1. Create a classic queue
2. call channel.QueueDeclarePassive(....., amqp.Table{amqp.QueueTypeArg: amqp.QueueTypeQuorum})
3. test err != nil

**Expected behavior**
If a classic queue exists with the same name and parameters, QueueDeclarePassive should return an error with the quorum queue type.

**Comment by lukebakken** [comment]
Thanks, this is actually is either a bug in RabbitMQ, or by design. I have asked the team about it.

**Comment by lukebakken** [comment]
@gildas arguments to the `Queue.Declare` method are ignored when the `passive` bit is set.

Here is the spec: https://www.rabbitmq.com/amqp-0-9-1-reference#queue.declare.passive

> When [the passive bit is] set, all other method fields except name and no-wait are ignored.

**Comment by lukebakken** [comment]
@gildas RabbitMQ is behaving according to the spec:

https://www.rabbitmq.com/amqp-0-9-1-reference#queue.declare.passive

> When [the passive bit is] set, all other method fields except name and no-wait are ignored.
