### ISSUE TITLE
Example Client: Implementation of a Consumer with reconnection support

### ISSUE THREAD

**Issue by andygrunwald** [rabbitmq/amqp091-go#40]
[`example_client_test.go`](https://github.com/rabbitmq/amqp091-go/blob/main/example_client_test.go) shows a great way how to build a Producer with reconnection support.

The Consuming part is not covering the reconnection support:
https://github.com/rabbitmq/amqp091-go/blob/51fade522e4d209b3cef22ff8c052d944524ac17/example_client_test.go#L257-L274

Even if [reconnection support](https://github.com/rabbitmq/amqp091-go/blob/main/README.md#non-goals) is mentioned as a non-goal for the library itself, I do think showcasing this in the example might be a good thing.

Right now, the implementation is only possible with a hack involved.
Mainly due to these two issues:

- https://github.com/rabbitmq/amqp091-go/issues/18
- https://github.com/rabbitmq/amqp091-go/issues/32

These deadlocks prevent the consumer delivery channel to be closed during an unexpected connection loss (e.g., when the RabbitMQ server goes down).

**Comment by DanielePalaia** [comment]
@andygrunwald Now that we understood what happened in https://github.com/rabbitmq/amqp091-go/issues/18 I think the example you propose can be just like an extension to the example we made in the documentation on how to handle channels for NotifyClose to avoid the deadlock for a consumer?

**Comment by andygrunwald** [comment]
Yeah, exactly. I was waiting for #18/#32.
I have it implemented incl. the deadlock in one of my projects.

If you are good with it, I would make a PR in the next few days and playback my implementation into the example client. Might take a few days.

**Comment by DanielePalaia** [comment]
Sure! good enough! Thanks @andygrunwald

**Comment by lukebakken** [comment]
This gives an example of auto-reconnection as well:

https://github.com/rabbitmq/amqp091-go/commit/4ce2c8e4e371338add82c3dc2df56f70d0dca601

**Comment by metalrex100** [comment]
@andygrunwald any updates with your example client?

**Comment by andygrunwald** [comment]
@metalrex100 Still on my list. My client is working in production since quite some time. Will check if I can make some time in the next days to push it back.
