### ISSUE TITLE
Possible deadlock on DeferredConfirmation.Wait()

### ISSUE THREAD

**Issue by ismurov** [rabbitmq/amqp091-go#46]
Hi, there. 👋

I'm starting to migrate from __github.com/streadway/amqp__ package and delve into the new features of this package. Currently I want to use the __PublishWithDeferredConfirm__ method and it doesn't look production-ready to me. The case in which the problem occurs is closing the connection while waiting for publication confirmation from the AMQP server. 

What I mean in more detail:
The type __Channel__ has a __shutdown__ method in which resources are cleared and closed, also here calls a [__Close__](https://github.com/rabbitmq/amqp091-go/blob/21ccfdea51148da4de39d35975fdd44480e979e2/confirms.go#L102) method of __confirms__ type. But this method does not properly clean up its resources such as __deferredConfirmations__ an awaiting __DeferredConfirmation__.
```go
dc, err := c.PublishWithDeferredConfirm(exchange, key, false, false, msg)
if err != nil {
	log.Fatalf("c.PublishWithDeferredConfirm: %s", err)
}
dc.Wait() // <- deadlock
```

Possible solution:
Add one more method in type __deferredConfirmations__ and call it from __confirms.Close__.
```go
// Close closes all awaiting DeferredConfirmation with Nack.
func (d *deferredConfirmations) Close() error {
	d.m.Lock()
	defer d.m.Unlock()

	for k, v := range d.confirmations {
		v.confirmation = Confirmation{DeliveryTag: k, Ack: false}
		v.wg.Done()
		delete(d.confirmations, k)
	}

	return nil
}
```
But it seems to me that such a situation should be handled with explicit error like ErrClosed. And it's breaking change of package API.

Package version: __v1.3.0__

**Comment by shifengbin** [comment]
the same reason [#44 ](https://github.com/rabbitmq/amqp091-go/pull/44)
