### ISSUE TITLE
Semver release

### ISSUE THREAD

**Issue by crazy-max** [rabbitmq/amqp091-go#7]
Can you create a release for this project and follow [semantic versioning](https://semver.org/) please? It is ok to start with `v0` version to allow backward incompatible changes. So `v0.1.0` could be a good start.

This will allow users to pin specific version instead of commit hash and setup auto-updating (e.g. Dependabot).

Thanks!

**Comment by Zerpet** [comment]
I just created `v1.1.0` release. Hope this helps!
