### ISSUE TITLE
this library has same issue

### ISSUE THREAD

**Issue by binlaniua** [rabbitmq/amqp091-go#83]
see (https://github.com/streadway/amqp/issues/489)

**Comment by lukebakken** [comment]
After researching this issue, it appears it would only surface if you are **NOT** using prefetch / QoS on the channel, and your consumer is slow, and you are using auto-ack. Is this correct?

**Comment by lukebakken** [comment]
Please see my comment - https://github.com/streadway/amqp/issues/489#issuecomment-1133647213

`autoAck` with a slow consumer is a bad practice with RabbitMQ. Use acks if you have slow consumers.
