### ISSUE TITLE
Channel Close gets stuck after closing a connection (via management UI)

### ISSUE THREAD

**Issue by gabo1208** [rabbitmq/amqp091-go#88]
I found an issue when:
1. I close a connection from the management UI (force close it, haven't got the time to test other possible connection close scenarios)
2. The program is waiting for a channel or connection notify close, and receives it
3. It checks if the channel is closed, it is not, then it proceeds to close it, but the method gets stuck and never returns

I caused my program to hang, now I'm just deleting the connection. 

Don't know if this is intended, but better to report it :)

**Comment by lukebakken** [comment]
Thanks for the report.

Can you share your code? If not, please share the following details:

* "The program is waiting for a channel or connection notify close, and receives it" - what do you mean? How exactly is your program "waiting" for the close notification?
* Is your program consuming, publishing, or both?
* Can you reproduce this issue _every_ time?

**Comment by lukebakken** [comment]
There is no reason to close a channel once the connection is closed, so https://github.com/knative-sandbox/eventing-rabbitmq/pull/778 is a valid fix.

I will see if I can reproduce this issue using this code:

https://github.com/rabbitmq/amqp091-go/tree/main/_examples/simple-producer

**Comment by lukebakken** [comment]
If I close the connections via the management UI for the consumer or producer, the shutdown happens as expected. So, I'm not really sure what's going on with your code 🤷 

There's a chance that #87 may fix your issue, so give version 1.4.0 a try once it's released.
